import express from 'express';import Spot from '../models/Spot.js';import ParkingRecord from '../models/ParkingRecord.js';import RateCard from '../models/RateCard.js';import {calculateFee} from '../utils/fee.js';import {cleanRateCard} from '../utils/rates.js';import auth from '../middleware/auth.js';
const r=express.Router();r.use(auth);const plate=p=>String(p||'').trim().toUpperCase();const compatible=t=>t==='ev'?['ev']:t==='compact'?['compact','standard']:['standard'];
async function rateFor(userId,type){return (await RateCard.findOne({garageId:userId,spotType:type}))||{firstHour:50,extraHour:30,dailyCap:200};}
async function closeRecord(rec,closedBy='checkout',at=new Date()){const rate=await rateFor(rec.userId,rec.vehicleType);rec.exitTime=at;rec.fee=calculateFee(rec.entryTime,at,rate);rec.closedBy=closedBy;rec.status='completed';await rec.save();await Spot.updateOne({_id:rec.spotId},{$set:{isOccupied:false}});return rec;}
r.post('/seed',async(req,res,next)=>{try{if(await Spot.countDocuments({ownerId:req.user.id}))return res.json({message:'Spots already seeded'});const a=[];for(let f=1;f<=3;f++)for(let n=1;n<=20;n++)a.push({ownerId:req.user.id,spotNumber:`F${f}-${String(n).padStart(2,'0')}`,floor:f,type:n<=5?'compact':n<=17?'standard':'ev'});await Spot.insertMany(a);res.status(201).json({message:'Created 60 spots'})}catch(e){next(e)}});
r.post('/rates/import',async(req,res,next)=>{try{const cleaned=cleanRateCard(req.body.rows||[]);if(!cleaned.length)return res.status(400).json({message:'No valid rate rows found'});for(const x of cleaned)await RateCard.findOneAndUpdate({garageId:req.user.id,spotType:x.spotType},{...x,garageId:req.user.id},{upsert:true,new:true});res.json({imported:cleaned.length,cleaned})}catch(e){next(e)}});
r.get('/rates',async(req,res,next)=>{try{res.json(await RateCard.find({garageId:req.user.id}).sort({spotType:1}))}catch(e){next(e)}});
r.get('/spots',async(req,res,next)=>{try{const{page=1,limit=60,sort='spotNumber',order='asc',type}=req.query;const allowed=['spotNumber','floor','type','isOccupied','createdAt'];const field=allowed.includes(sort)?sort:'spotNumber';const q={ownerId:req.user.id,...(type?{type}:{})};const data=await Spot.find(q).sort({[field]:order==='desc'?-1:1}).skip((page-1)*limit).limit(Number(limit));res.json({data,page:Number(page),limit:Number(limit),total:await Spot.countDocuments(q)})}catch(e){next(e)}});
r.get('/spots/ev',async(req,res,next)=>{try{res.json(await Spot.find({ownerId:req.user.id,type:'ev',isOccupied:false}).sort({floor:1,spotNumber:1}))}catch(e){next(e)}});
r.get('/history',async(req,res,next)=>{try{const{page=1,limit=10,sort='createdAt',order='desc',search=''}=req.query;const allowed=['createdAt','entryTime','exitTime','fee','plateNumber','status'];const field=allowed.includes(sort)?sort:'createdAt';const q={userId:req.user.id,...(search?{plateNumber:{$regex:plate(search)}}:{})};const data=await ParkingRecord.find(q).populate('spotId').sort({[field]:order==='asc'?1:-1}).skip((page-1)*limit).limit(Number(limit));res.json({data,page:Number(page),limit:Number(limit),total:await ParkingRecord.countDocuments(q)})}catch(e){next(e)}});
r.get('/vehicle/:plate',async(req,res,next)=>{try{res.json(await ParkingRecord.find({userId:req.user.id,plateNumber:plate(req.params.plate)}).populate('spotId').sort({createdAt:-1}))}catch(e){next(e)}});
r.post('/check-in',async(req,res,next)=>{try{const p=plate(req.body.plateNumber),t=req.body.vehicleType;if(!p||!['compact','standard','ev'].includes(t))return res.status(400).json({message:'Plate and vehicle type required'});if(await ParkingRecord.findOne({userId:req.user.id,plateNumber:p,status:'active'}))return res.status(409).json({message:'Vehicle already parked'});const s=await Spot.findOneAndUpdate({ownerId:req.user.id,type:{$in:compatible(t)},isOccupied:false},{$set:{isOccupied:true}},{new:true,sort:{floor:1,spotNumber:1}});if(!s)return res.status(409).json({message:'No compatible spot available'});try{const rec=await ParkingRecord.create({plateNumber:p,vehicleType:t,spotId:s._id,userId:req.user.id});res.status(201).json(await rec.populate('spotId'))}catch(e){await Spot.updateOne({_id:s._id},{$set:{isOccupied:false}});throw e}}catch(e){next(e)}});
r.post('/check-out',async(req,res,next)=>{try{const p=plate(req.body.plateNumber),rec=await ParkingRecord.findOne({userId:req.user.id,plateNumber:p,status:'active'});if(!rec)return res.status(404).json({message:'Active vehicle not found'});res.json(await closeRecord(rec))}catch(e){next(e)}});
r.post('/transfer',async(req,res,next)=>{try{const from=plate(req.body.fromPlate),to=plate(req.body.toPlate);if(!from||!to)return res.status(400).json({message:'fromPlate and toPlate required'});if(await ParkingRecord.findOne({userId:req.user.id,plateNumber:to,status:'active'}))return res.status(409).json({message:'Destination plate already has an active session'});const rec=await ParkingRecord.findOne({userId:req.user.id,plateNumber:from,status:'active'});if(!rec)return res.status(404).json({message:'Open source session not found'});rec.plateNumber=to;await rec.save();res.json(await rec.populate('spotId'))}catch(e){next(e)}});
r.post('/clock',async(req,res,next)=>{try{const at=req.body.now?new Date(req.body.now):new Date();if(Number.isNaN(at.getTime()))return res.status(400).json({message:'Invalid now timestamp'});const sessions=await ParkingRecord.find({userId:req.user.id,status:'active',entryTime:{$lte:new Date(at.getTime()-24*60*60*1000)}});const closed=[];for(const rec of sessions)closed.push(await closeRecord(rec,'clock',at));res.json({closedCount:closed.length,closed})}catch(e){next(e)}});
export default r;
